# Generated by Django 4.1.2 on 2022-10-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='font_awesome',
            field=models.CharField(default='fa-', max_length=75, verbose_name='Font-awesome'),
        ),
    ]
